"""add_access_token_to_provider_accounts

Revision ID: 73ef66a227f8
Revises: d9775317e949
Create Date: 2025-06-03 22:45:05.911016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73ef66a227f8'
down_revision: Union[str, None] = 'd9775317e949'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_accounts', sa.Column('access_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider_accounts', 'access_token')
    # ### end Alembic commands ###
