"""Add display fields and constraints to achievements

Revision ID: 9d1076f37ae5
Revises: a1a364b7f2e3
Create Date: 2025-06-01 06:01:19.239687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d1076f37ae5'
down_revision: Union[str, None] = 'a1a364b7f2e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievements', sa.Column('display_name', sa.String(), nullable=True))
    op.add_column('achievements', sa.Column('description', sa.String(), nullable=True))
    op.add_column('achievements', sa.Column('icon_url', sa.String(), nullable=True))
    op.add_column('achievements', sa.Column('icon_gray_url', sa.String(), nullable=True))
    op.add_column('achievements', sa.Column('hidden', sa.Boolean(), nullable=True))
    op.add_column('achievements', sa.Column('default_value', sa.Integer(), nullable=True))
    op.add_column('achievements', sa.Column('percent', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('achievements', 'percent')
    op.drop_column('achievements', 'default_value')
    op.drop_column('achievements', 'hidden')
    op.drop_column('achievements', 'icon_gray_url')
    op.drop_column('achievements', 'icon_url')
    op.drop_column('achievements', 'description')
    op.drop_column('achievements', 'display_name')
    # ### end Alembic commands ###
