"""Battlenet Sync Implementation

Revision ID: d117bc3a3b9f
Revises: 47ff5396534a
Create Date: 2025-06-01 21:34:41.271897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd117bc3a3b9f'
down_revision: Union[str, None] = '47ff5396534a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievement_credits', sa.Column('character_name', sa.String(), nullable=True))
    op.add_column('achievement_credits', sa.Column('realm_slug', sa.String(), nullable=True))
    op.drop_constraint(op.f('unique_credit_per_provider_achievement'), 'achievement_credits', type_='unique')
    op.create_index(op.f('ix_achievement_credits_character_name'), 'achievement_credits', ['character_name'], unique=False)
    op.create_index(op.f('ix_achievement_credits_realm_slug'), 'achievement_credits', ['realm_slug'], unique=False)
    op.create_unique_constraint('unique_credit_per_provider_achievement_character', 'achievement_credits', ['provider_account_id', 'achievement_id', 'character_name', 'realm_slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_credit_per_provider_achievement_character', 'achievement_credits', type_='unique')
    op.drop_index(op.f('ix_achievement_credits_realm_slug'), table_name='achievement_credits')
    op.drop_index(op.f('ix_achievement_credits_character_name'), table_name='achievement_credits')
    op.create_unique_constraint(op.f('unique_credit_per_provider_achievement'), 'achievement_credits', ['provider_account_id', 'achievement_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('achievement_credits', 'realm_slug')
    op.drop_column('achievement_credits', 'character_name')
    # ### end Alembic commands ###
