"""add achievement_credits

Revision ID: d9775317e949
Revises: d117bc3a3b9f
Create Date: 2025-06-03 10:26:49.140267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9775317e949'
down_revision: Union[str, None] = 'd117bc3a3b9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add column with a default so existing rows are filled
    op.add_column(
    'provider_accounts',
        sa.Column('tap_contribution', sa.Integer(), nullable=False, server_default='0')
    )

# Step 2 (Optional): Remove server_default if you don't want it persisted
    op.alter_column('provider_accounts', 'tap_contribution', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider_accounts', 'tap_contribution')
    # ### end Alembic commands ###
